/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mavenproject1;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Scanner;
import javax.swing.JOptionPane;



/**
 *
 * @author hp
 */
public class NewJFrame  extends javax.swing.JFrame 
{

    
    
    
    public NewJFrame() {
       
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        save = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        search = new javax.swing.JButton();
        update = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Name");

        jLabel2.setText("Salary");

        jLabel3.setText(" ID");

        jLabel4.setText("Birthdate");

        jLabel5.setText("Department");

        jTextField1.setBackground(new java.awt.Color(204, 204, 255));
        jTextField1.setCaretColor(new java.awt.Color(255, 102, 102));
        jTextField1.setDisabledTextColor(new java.awt.Color(204, 204, 255));
        jTextField1.setSelectionColor(new java.awt.Color(102, 102, 255));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.setBackground(new java.awt.Color(204, 204, 255));

        jTextField3.setBackground(new java.awt.Color(204, 204, 255));
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jTextField4.setBackground(new java.awt.Color(204, 204, 255));

        jTextField5.setBackground(new java.awt.Color(204, 204, 255));

        save.setBackground(new java.awt.Color(51, 153, 255));
        save.setText("save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        delete.setBackground(new java.awt.Color(51, 102, 255));
        delete.setText("delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        search.setBackground(new java.awt.Color(51, 153, 255));
        search.setText("search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        update.setBackground(new java.awt.Color(51, 153, 255));
        update.setText("update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(delete)
                    .addComponent(save))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(search, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(update, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(209, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(save)
                    .addComponent(search))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(delete)
                    .addComponent(update))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
      
    
    
    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        
        
      String N= jTextField1.getText();
      String S= jTextField2.getText();
      String E=  jTextField3.getText();
      String B=   jTextField4.getText();
      String D=   jTextField5.getText();
       //  System.out.println(jTextField1.getText()); 
        
       
       
       
        try{
            FileWriter FW=new FileWriter("F1.txt",true);
            FW.write(N+","+S+","+E+","+B+","+D);
            FW.write(System.getProperty("line.separator"));
            FW.close();
            JOptionPane.showMessageDialog(null, "Success");
            setVisible(false);
            new NewJFrame().setVisible(true);
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "ERROR");
                   
        }
         
        
    }//GEN-LAST:event_saveActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
       
      



    }//GEN-LAST:event_jTextField1ActionPerformed
     int linenum;
    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        try
        {
      
              int flag=0;
               linenum=0;
               String N= jTextField1.getText();
               String S= jTextField2.getText();
               String E= jTextField3.getText();
               String B= jTextField4.getText();
               String D=jTextField5.getText();
            
            
            
            
            
            
            
            
            BufferedReader reader = new BufferedReader(new FileReader("F1.txt"));
            String line=reader.readLine();
            String[] result = null  ;
           
           while(line!=null&&flag!=1 )
           {
             
                  //  System.out.println(line); 
            
             for (int i =0 ;i<line.length();i++)
              {
                    if (line.charAt(i)==',')
                     {
                     //line=reader.readLine();
                     result = line.split(",");
                    
                  //    Arrays.toString(result);
                     }
                    
                    
              }
             
                     //  for (int j =0 ;j<=5;j++)
                      // {  
                     
                       if (result[0].equals(N))
                       {flag=1;
                           jTextField1.setText(result[0]);
                       jTextField2.setText(result[1]);
                       jTextField3.setText(result[2]);
                       jTextField4.setText(result[3]);
                       jTextField5.setText(result[4]);
                      System.out.println(line); }
                       
                      else if(result[1].equals(S))
                      {flag=1;
                          jTextField1.setText(result[0]);
                       jTextField2.setText(result[1]);
                       jTextField3.setText(result[2]);
                       jTextField4.setText(result[3]);
                       jTextField5.setText(result[4]);
                       System.out.println(line); }
                      
                       else if(result[2].equals(E))
                       {flag=1;
                           jTextField1.setText(result[0]);
                       jTextField2.setText(result[1]);
                       jTextField3.setText(result[2]);
                       jTextField4.setText(result[3]);
                       jTextField5.setText(result[4]);
                       System.out.println(line); }
                       
                       else  if (result[3].equals(B))
                       {flag=1;
                           jTextField1.setText(result[0]);
                       jTextField2.setText(result[1]);
                       jTextField3.setText(result[2]);
                       jTextField4.setText(result[3]);
                       jTextField5.setText(result[4]);
                       System.out.println(line); }
                       
                       else  if (result[4].equals(D))
                       {flag=1;
                           jTextField1.setText(result[0]);
                       jTextField2.setText(result[1]);
                       jTextField3.setText(result[2]);
                       jTextField4.setText(result[3]);
                       jTextField5.setText(result[4]);
                       System.out.println(line); }
                       
                      // }
                    // }
         
              
              
              
              
               //  }
             
              line=reader.readLine();  
               linenum ++;
               System.out.println("linenum after search="+linenum);    
              
             }  
              
       
        
       
        
         } 
        
        
         catch(IOException e)
         {JOptionPane.showMessageDialog(null, "error");}
        
    }//GEN-LAST:event_searchActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
       try  
        { 
            System.out.println("linenum in befor update="+linenum);
            
                    String N= jTextField1.getText();
                    String S= jTextField2.getText();
                    String E=  jTextField3.getText();
                    String B=   jTextField4.getText();
                    String D=   jTextField5.getText();
                    String[] result = null  ;
                    ArrayList<String> R = new ArrayList<String>();
       
          
             BufferedReader reader = new BufferedReader(new FileReader("F1.txt"));
            
              String line=reader.readLine();
          
                 
                  int linenumcount=1;
                 while (line != null ) 
             {
                 if (linenumcount==linenum)
                 {        for (int i =0 ;i<line.length();i++)
                        {if (line.charAt(i)==','){result = line.split(",");}
                         
                        }
                     break;
                 }
                 else{ 
                     linenumcount ++;
                     R.add(line);
                     line=reader.readLine();  }
                  
             }
                     if (result[0]!=N)
                        line = line.replace(result[0] , N);
                       if(result[1]!=S)
                       line = line.replace(result[1] , S);
                       if(result[2]!=E)
                      line = line.replace(result[2] , E);
                         if (result[3]!=B)
                     line = line.replace(result[3] , B);
                         if (result[4]!=D)
                     line = line.replace(result[4] ,D);
                         
                         
                         
                  System.out.println("linenum in after update="+linenum);
                  System.out.println(line); 
                  System.out.println("File updated successfully.");
                       R.add(line);
                
              
             
               
              
              BufferedWriter writer = new BufferedWriter(new FileWriter("F1.txt"));

              
                 for (String item : R)
                    {
                     writer.write(item);
                      writer.newLine(); 
                     }
                
                writer.close();
                
                
            } 
       catch (IOException e) 
        {
            e.printStackTrace();
            System.err.println("An error occurred while updating the file.");
        }
      
        
        
         
    }//GEN-LAST:event_updateActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        try
        {
           System.out.println("linenum in  befor update="+linenum);
           BufferedReader file = new BufferedReader(new FileReader("F1.txt"));
          
        
       
                  int flag=0;
                    String N= jTextField1.getText();
                    String S= jTextField2.getText();
                    String E=  jTextField3.getText();
                    String B=   jTextField4.getText();
                    String D=   jTextField5.getText();
                  ArrayList<String> R = new ArrayList<String>();
       
           
            
                  String line= file.readLine();
          
                 // FileWriter fileOut = new FileWriter("F1.txt",true);
                  
                  
              int linenumcount=1;
             while (line !=null ||flag!=1 ) 
             {
                 if (linenumcount==linenum)
                 {    
                      line="";
                    flag=1;
                    
                 }
                 else
                 {  
                 R.add(line);
                 }
                 linenumcount ++;
                 line= file.readLine();  
             }
               
                   BufferedWriter writer = new BufferedWriter(new FileWriter("F1.txt"));

                    for (String item : R)
                    {
                     writer.write(item);
                      writer.newLine(); 
                     }
                     System.out.println("linenum in afterdelete="+linenum);
                     
                     writer.close();
                   
                    
                    
   
           
         }
        catch (Exception e) {e.printStackTrace();
            System.err.println("An error occurred while deleted the file.");}
        
      
    
   
  
    
    }//GEN-LAST:event_deleteActionPerformed

   
    public static void main(String args[]) 
    {
     
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run() 
            {
                //new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton delete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    public javax.swing.JButton save;
    public javax.swing.JButton search;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
